[package]
name = "py_fastmath"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "py_fastmath"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3.workspace = true
numpy.workspace = true
ndarray.workspace = true
rayon.workspace = true
